#!/bin/bash

# Check if a database name is provided
if [ -z "$1" ]; then
  echo "⚠️  Please provide the database name as an argument."
  echo "Usage:"
  echo "  odoonix-duplicate my_database target_database"
  exit 1
fi


CMD="/var/lib/odoo/odoo-bin"
DB_NAME="$1"
DB_TARGET_NAME="$2"
# Path to the Odoo configuration file (change this if needed)
CONFIG_FILE="/etc/odoo/odoo.conf"
GLOBAL_OPTIONS="--stop-after-init --without-demo=all --no-http"


# Run the update
echo "🚀 duplicate database: $DB_NAME ..."
$CMD db \
    -c "$CONFIG_FILE" \
    duplicate "$DB_NAME" \
    "$DB_TARGET_NAME"

# Check the result
if [ $? -eq 0 ]; then
  echo "✅ duplicate completed successfully."
else
  echo "❌ An error occurred during the update."
fi
