#!/bin/bash

set -e

CMD="/var/lib/odoo/odoo-bin"
CONFIG_FILE="/etc/odoo/odoo.conf"
GLOBAL_OPTIONS="--config $CONFIG_FILE  --log-level=debug"

# Default values
FORCE=false

usage() {
    cat <<EOF
Usage:
  $(basename "$0") [OPTIONS] DATABASE_NAME

Options:
  --force                   Delete database if it already exists
  -h, --help                Show this help

Examples:
  $(basename "$0") mydb

  $(basename "$0") \
      --force \
      mydb

EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)
            FORCE=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
        *)
            DB_NAME="$1"
            shift
            ;;
    esac
done

# Check database name
if [[ -z "$DB_NAME" ]]; then
    echo "Database name is required."
    usage
    exit 1
fi


# Build command
ARGS=(
    db
    drop
    "$DB_NAME"
)

echo
echo "Database : $DB_NAME"
echo
read -rp "Are you sure you want to drop this database? [y/N]: " answer

case "$answer" in
    [Yy]|[Yy][Ee][Ss])
        echo "🚀 Starting..."
        ;;
    *)
        echo "❌ Operation cancelled."
        exit 0
        ;;
esac
echo "🚀 Droping database: $DB_NAME"


"$CMD" "${ARGS[@]}"

echo
echo "✅ Drop completed successfully."
echo "   Database : $DB_NAME"

