#!/bin/bash

# Check if a database name is provided
if [ -z "$1" ]; then
  echo "⚠️  Please provide the database name as an argument."
  echo "Usage:"
  echo "  odoonix-drop my_database"
  exit 1
fi


CMD="/var/lib/odoo/odoo-bin"
DB_NAME="$1"
DB_TARGET_NAME="$2"
# Path to the Odoo configuration file (change this if needed)
CONFIG_FILE="/etc/odoo/odoo.conf"
GLOBAL_OPTIONS="--stop-after-init --without-demo=all --no-http --http-port=8889""


# Run the drop
echo "🚀 drop database: $DB_NAME ..."
$CMD db \
    -c "$CONFIG_FILE" \
    drop "$DB_NAME" 

# Check the result
if [ $? -eq 0 ]; then
  echo "✅ drop completed successfully."
else
  echo "❌ An error occurred during the update."
fi

