#!/bin/bash

# Check if a database name is provided
if [ -z "$1" ]; then
  echo "⚠️  Please provide the database name as an argument."
  echo "Usage:"
  echo "  odoo-shell my_database"
  exit 1
fi


CMD="/var/lib/odoo/odoo-bin"
DB_NAME="$1"
# Path to the Odoo configuration file (change this if needed)
CONFIG_FILE="/etc/odoo/odoo.conf"
GLOBAL_OPTIONS="--stop-after-init --without-demo=all --no-http --http-port=8889 --log-level=debug"


# Run the update
echo "🚀 Openning database: $DB_NAME ..."
$CMD shell -c "$CONFIG_FILE" -d "$DB_NAME" $GLOBAL_OPTIONS



