#!/bin/bash

set -e

CMD="/var/lib/odoo/odoo-bin"
CONFIG_FILE="/etc/odoo/odoo.conf"
GLOBAL_OPTIONS="--config $CONFIG_FILE"

# Default values
NO_FILESTORE=false
FORMAT="zip"


usage() {
    cat <<EOF
Usage:
  $(basename "$0") [OPTIONS] DATABASE_NAME

Options:
  --format  zip,dump        If provided, database is dumped used the specified format. Supported formats are zip (default), dump (pg_dump format).
  --no-filestore            Zip database is dumped without filestore
  --force                   Force to create dump
  -h, --help                Show this help

Examples:
  $(basename "$0") mydb

  $(basename "$0") \
      --force \
      --no-filestore \
      --format zip \
      mydb

EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)
            FORCE=true
            shift
            ;;
        --format)
            FORMAT="$2"
            shift 2
            ;;
        --no-filestore)
            NO_FILESTORE=true
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
        *)
            DB_NAME="$1"
            shift
            ;;
    esac
done

# Check database name
if [[ -z "$DB_NAME" ]]; then
    echo "Database name is required."
    usage
    exit 1
fi


# Build command
BACKUP_FILENAME="/var/lib/odoo-data/backup/${DB_NAME}-$(date +%s).zip"
ARGS=(
    db
    --config "$CONFIG_FILE"
    dump
    "$DB_NAME"
    "BACKUP_FILENAME"
)

[[ "$NO_FILESTORE" == true ]] && ARGS+=(--no-filestore)


echo
echo "Database : $DB_NAME"
echo "Format   : $FORMAT"
echo
read -rp "Are you sure you want to backup this database? [y/N]: " answer

case "$answer" in
    [Yy]|[Yy][Ee][Ss])
        echo "🚀 Starting..."
        ;;
    *)
        echo "❌ Operation cancelled."
        exit 0
        ;;
esac
echo "🚀 Dumping database: $DB_NAME"

"$CMD" "${ARGS[@]}"

echo
echo "✅ Dump completed successfully."
echo "   Database : $DB_NAME"
echo "   Format   : $FORMAT"



