name: publishpublish
run-name: ${{ github.actor }} build new image
on: [push]
jobs:
       publish-odoo16-image:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@v2
                     - uses: docker/login-action@v1
                       with:
                              registry: ghcr.io
                              username: ${{ github.actor }}
                              password: ${{ secrets.GITHUB_TOKEN }}
                     - name: Build the Odoo Runner 17.0 Docker image
                       run: |
                              timetag=(`date +%Y%M%d`)
                              docker build . --tag ghcr.io/odoonix/odoo-runner:17.0.${timetag} --tag ghcr.io/odoonix/odoo-runner:17.0
                              docker push ghcr.io/odoonix/odoo-runner:17.0
                              docker push ghcr.io/odoonix/odoo-runner:17.0.${timetag}
